version: "3"
services:
  lucky-pick-be:
    container_name: lucky-pick-be
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - path: ./server/.env
        required: true
    ports:
      - "7000:7000"
    networks:
      - frontend
  lucky-pick-fe:
    container_name: lucky-pick-fe
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /app/web/node_modules
    networks:
      - frontend
    env_file:
      - path: ./client/.env
        required: true

networks:
  frontend:
